services:
  - type: web
    name: vendor-onboarding-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: REPLY_TO_EMAIL
        value: AP3@SeacrestSW.com
      - key: APP_USERNAME
        sync: false
      - key: APP_PASSWORD_HASH
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
